#!/bin/bash
# deploy-frontend.sh <env>
# Builds and deploys the Next.js frontend.
# Reads foundation + all service outputs directly from S3 terraform state.
# Run standalone whenever frontend code changes or after any service deploy.
#
# Usage:
#   scripts/deploy-frontend.sh dev
#   scripts/deploy-frontend.sh prod
#
# Optional: Configure Cognito OAuth by passing environment variables:
#   COGNITO_DOMAIN=<domain> \
#   COGNITO_USER_POOL_ID=<pool_id> \
#   COGNITO_APP_CLIENT_ID=<client_id> \
#   COGNITO_REGION=<region> \
#   scripts/deploy-frontend.sh prod
#
# If not provided, defaults to hardcoded values from terraform outputs.
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "❌ Usage: $0 <environment>"
  echo "   Environments: dev | test | prod"
  exit 1
fi

ENV="$1"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FOUNDATION_TF="$ROOT/terraform/foundation"

AWS_PROFILE="${AWS_PROFILE:-terraform}"
ACCOUNT_ID=$(aws sts get-caller-identity --profile "$AWS_PROFILE" --query Account --output text)
STATE_BUCKET="twin-terraform-state-${ACCOUNT_ID}"
LOCK_TABLE="twin-terraform-locks"

# ---------------------------------------------------------------------------
# Read foundation outputs from S3 state
# ---------------------------------------------------------------------------

echo "📡 Reading foundation outputs from state..."
terraform -chdir="$FOUNDATION_TF" init -input=false \
  -backend-config="bucket=${STATE_BUCKET}" \
  -backend-config="key=foundation/${ENV}/terraform.tfstate" \
  -backend-config="dynamodb_table=${LOCK_TABLE}" \
  -reconfigure -no-color > /dev/null

CLOUDFRONT_URL=$(terraform -chdir="$FOUNDATION_TF" output -raw cloudfront_url)
CLOUDFRONT_ID=$(terraform -chdir="$FOUNDATION_TF" output -raw cloudfront_distribution_id)
FRONTEND_BUCKET=$(terraform -chdir="$FOUNDATION_TF" output -raw s3_frontend_bucket)
CUSTOM_URL=$(terraform -chdir="$FOUNDATION_TF" output -raw custom_domain_url 2>/dev/null || echo "")

echo "🌐 Deploying frontend to environment: ${ENV}"
echo "   Frontend bucket : ${FRONTEND_BUCKET}"
echo "   CloudFront      : ${CLOUDFRONT_URL}"
echo ""

# ---------------------------------------------------------------------------
# Collect service API URLs from S3 state for each deployed service
# ---------------------------------------------------------------------------

SERVICE_NAMES=()
SERVICE_URLS=()

for SERVICE_DIR in "$ROOT/terraform/services"/*/; do
  SERVICE=$(basename "$SERVICE_DIR")
  [[ "$SERVICE" == _* ]] && continue
  SERVICE_TF="$ROOT/terraform/services/${SERVICE}"

  echo "   Checking service: ${SERVICE}..."

  if ! terraform -chdir="$SERVICE_TF" init -input=false \
    -backend-config="bucket=${STATE_BUCKET}" \
    -backend-config="key=services/${SERVICE}/${ENV}/terraform.tfstate" \
    -backend-config="dynamodb_table=${LOCK_TABLE}" \
    -reconfigure -no-color > /dev/null 2>&1; then
    echo "   ⚠️  Could not init ${SERVICE} — skipping."
    continue
  fi

  API_URL=$(terraform -chdir="$SERVICE_TF" output -raw public_url 2>/dev/null || echo "")
  # Fall back to api_gateway_url for services that predate the public_url output
  [[ -z "$API_URL" ]] && API_URL=$(terraform -chdir="$SERVICE_TF" output -raw api_gateway_url 2>/dev/null || echo "")
  SVC_NAME=$(terraform -chdir="$SERVICE_TF" output -raw service_name 2>/dev/null || echo "")

  if [[ -n "$API_URL" && -n "$SVC_NAME" ]]; then
    SERVICE_NAMES+=("$SVC_NAME")
    SERVICE_URLS+=("$API_URL")
    echo "   Found: ${SVC_NAME} → ${API_URL}"
  else
    echo "   ⚠️  No deployed state for ${SERVICE} in '${ENV}' — skipping."
  fi
done

echo ""

# Determine canonical frontend URL (custom domain takes priority)
FRONTEND_URL="${CUSTOM_URL:-$CLOUDFRONT_URL}"
# Ensure trailing slash for Cognito redirect compatibility
[[ "$FRONTEND_URL" != */ ]] && FRONTEND_URL="${FRONTEND_URL}/"

# ---------------------------------------------------------------------------
# Build .env.production
# ---------------------------------------------------------------------------

ENV_FILE="$ROOT/frontend/.env.production"

{
  echo "# Auto-generated by deploy-frontend.sh — do not edit manually"
  echo "# Environment: ${ENV}"
  echo ""

  # Emit NEXT_PUBLIC_<SERVICE_NAME_UPPER>_URL for every deployed service
  for i in "${!SERVICE_NAMES[@]}"; do
    svc_name="${SERVICE_NAMES[$i]}"
    api_url="${SERVICE_URLS[$i]}"
    # Convert "twin-api" → "TWIN_API", "trading" → "TRADING"
    VAR_NAME="NEXT_PUBLIC_$(echo "$svc_name" | tr '[:lower:]-' '[:upper:]_')_URL"
    echo "${VAR_NAME}=${api_url}"
  done

  echo ""
  echo "# Cognito OAuth Configuration"
  echo "NEXT_PUBLIC_COGNITO_DOMAIN=${COGNITO_DOMAIN:-us-east-1uhz7yreuq.auth.us-east-1.amazoncognito.com}"
  echo "NEXT_PUBLIC_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID:-us-east-1_uhz7yREuQ}"
  echo "NEXT_PUBLIC_COGNITO_CLIENT_ID=${COGNITO_APP_CLIENT_ID:-2vn45ed6rbe1c9cg58b2vgpt5u}"
  echo "NEXT_PUBLIC_COGNITO_REGION=${COGNITO_REGION:-us-east-1}"
  echo ""
  echo "# Cognito OAuth Redirect URLs"
  echo "NEXT_PUBLIC_COGNITO_REDIRECT_SIGN_IN=${FRONTEND_URL}"
  echo "NEXT_PUBLIC_COGNITO_REDIRECT_SIGN_OUT=${FRONTEND_URL}"
} > "$ENV_FILE"

echo "📝 Written ${ENV_FILE}:"
grep -v "^#" "$ENV_FILE" | grep -v "^$"
echo ""

# ---------------------------------------------------------------------------
# Build frontend
# ---------------------------------------------------------------------------

cd "$ROOT/frontend"
echo "📦 Installing dependencies..."
npm install --silent

echo "🔨 Building Next.js static export..."
npm run build

# ---------------------------------------------------------------------------
# Upload to S3 and invalidate CloudFront cache
# ---------------------------------------------------------------------------

echo "☁️  Syncing to S3..."
aws s3 sync ./out "s3://${FRONTEND_BUCKET}/" --delete --profile "${AWS_PROFILE:-terraform}"

echo "🔄 Invalidating CloudFront cache..."
aws cloudfront create-invalidation \
  --distribution-id "${CLOUDFRONT_ID}" \
  --paths "/*" \
  --profile "${AWS_PROFILE:-terraform}" \
  --output text --query 'Invalidation.Id'

echo ""
echo "✅ Frontend deployed!"
echo "   CloudFront URL : ${CLOUDFRONT_URL}"
[[ -n "${CUSTOM_URL:-}" ]] && echo "   Custom domain  : ${CUSTOM_URL}"
